In [2]:
import numpy as np

In [3]:
minha_lista=[1,2,3]

In [4]:
minha_lista

[1, 2, 3]

In [5]:
#criando um numpy array dado que ja tenha uma lista(1 dimensao)
np.array(minha_lista)

array([1, 2, 3])

In [8]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]


In [9]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
arr = np.zeros(3)

In [14]:
arr

array([0., 0., 0.])

In [16]:
arr = np.zeros((5,5))

In [17]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.random.rand(5)

array([0.78739905, 0.73470875, 0.89805927, 0.48055812, 0.99565757])

In [22]:
np.random.rand(5)*100

array([37.12963135, 82.37882283, 83.80061224, 72.35904938, 48.64178513])

In [23]:
np.random.rand(5,4)*100

array([[29.03133059, 68.67318109, 32.03934551, 87.69429664],
       [95.21718283, 96.85361979, 27.61895828, 25.00038421],
       [19.4379376 ,  7.68326113, 37.52641715, 94.90697251],
       [76.10376341, 22.63477213, 66.96976279,  1.27559453],
       [53.42269861, 89.40293607, 76.09030721, 91.23860063]])

In [24]:
np.random.rand(5)

array([ 0.8326433 , -2.77436465, -1.36046321,  0.40399636])

In [25]:
np.random.randint(0,100,10)

array([35, 23, 21, 60, 35, 16, 16, 15, 95,  8])

In [28]:
np.round(np.random.rand(5)*100,0)

array([55., 58., 53., 16., 50.])

In [29]:
arr = np.random.rand(25)

In [30]:
arr

array([0.03991644, 0.69626064, 0.18814251, 0.61766929, 0.35521658,
       0.9817918 , 0.49841552, 0.50427515, 0.86429315, 0.03254051,
       0.61010718, 0.99923573, 0.37169515, 0.10258171, 0.1543037 ,
       0.1022394 , 0.29093366, 0.60392211, 0.76508028, 0.22553815,
       0.82770495, 0.5814095 , 0.59340862, 0.79210043, 0.40998137])

In [31]:
arr.reshape((5,5))

array([[0.03991644, 0.69626064, 0.18814251, 0.61766929, 0.35521658],
       [0.9817918 , 0.49841552, 0.50427515, 0.86429315, 0.03254051],
       [0.61010718, 0.99923573, 0.37169515, 0.10258171, 0.1543037 ],
       [0.1022394 , 0.29093366, 0.60392211, 0.76508028, 0.22553815],
       [0.82770495, 0.5814095 , 0.59340862, 0.79210043, 0.40998137]])

In [32]:
arr = arr.reshape((5,5))

In [33]:
arr.shape

(5, 5)

In [34]:
arr.max()

0.9992357319025137

In [35]:
arr.argmax()

11